#Whether or not XyCraft uses neo or internal energy handling with items. The intended way is to use internal.
#Allowed Values: Neo, Xynergy
energy_paradigm = "Xynergy"

[Experiments]
	#Unfinished, unpolished, possibly INCREDIBLY broken features. Please, avoid turning this on for a world file you are wanting to play.
	incomplete_features = false
